[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "nft"
  included_files = ["netlify/functions/**", "node_modules/pdfmake/build/**"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
